# Generated by Django 5.0.6 on 2024-06-15 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_answer_question_qna_db_downvotes_qna_db_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='qid',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answr',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='auser',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='pquestion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='puser',
            field=models.CharField(max_length=255),
        ),
    ]
