# Generated by Django 5.0.6 on 2024-06-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_remove_qna_db_downvotes_remove_qna_db_upvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna_db',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qna_db',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
