# Generated by Django 5.0.6 on 2024-06-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_qna_db_downvotes_qna_db_upvotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=100)),
                ('answr', models.CharField(max_length=1000)),
                ('auser', models.CharField(max_length=100)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pquestion', models.CharField(max_length=1000)),
                ('puser', models.CharField(max_length=100)),
            ],
        ),
    ]
